### ISSUE TITLE
Because tkinter was not found in the package registry and you require tkinter,

### ISSUE THREAD

**Issue by tqangxl** [EdwardDali/erag#3]
PS D:\Lib\Dev\AI\ERAG\ERAG> uv venv erag -p 3.10.14
Using Python 3.10.14 interpreter at: C:\Users\James\AppData\Roaming\uv\data\python\cpython-3.10.14-windows-x86_64-none\python.exe
Creating virtualenv at: erag
Activate with: erag\Scripts\activate
PS D:\Lib\Dev\AI\ERAG\ERAG> cd .\erag\
PS D:\Lib\Dev\AI\ERAG\ERAG\erag> uv pip install -r requirements.txt -U
error: Failed to download: `en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0-py3-none-any.whl`
  Caused by: Failed to unzip wheel: en_core_web_sm-3.5.0-py3-none-any.whl
  Caused by: an upstream reader returned an error: io error occurred: Request failed after 1 retries
  Caused by: io error occurred: Request failed after 1 retries
  Caused by: Request failed after 1 retries
  Caused by: error sending request for url (https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0-py3-none-any.whl)
  Caused by: client error (SendRequest)
  Caused by: connection error
  Caused by: peer closed connection without sending TLS close_notify: https://docs.rs/rustls/latest/rustls/manual/_03_howto/index.html#unexpected-eof
PS D:\Lib\Dev\AI\ERAG\ERAG\erag> uv pip install -r requirements.txt -U
  x No solution found when resolving dependencies:
  `-> Because tkinter was not found in the package registry and you require tkinter, we can conclude that the
      requirements are unsatisfiable.
PS D:\Lib\Dev\AI\ERAG\ERAG\erag> uv pip install tkinter
  x No solution found when resolving dependencies:
  `-> Because tkinter was not found in the package registry and you require tkinter, we can conclude that the
      requirements are unsatisfiable.
PS D:\Lib\Dev\AI\ERAG\ERAG\erag>

**Comment by EduardTalianu** [comment]
Failed download of en-core-web-sm:
The error suggests a network issue when trying to download the spaCy model. This could be due to temporary network problems or GitHub rate limiting. To resolve this:
a. Try running the command again after a short wait.
b. If the issue persists, you can manually download the model and install it:

Download the .whl file from the URL mentioned in the error message
Install it using: uv pip install path/to/downloaded/en_core_web_sm-3.5.0-py3-none-any.whl

tkinter not found:
tkinter is typically included with Python installations, but it might not be recognized in your environment. Here's how to address this:
a. Ensure Python was installed with tkinter:

On Windows, during Python installation, make sure "tcl/tk and IDLE" is selected.
If you need to reinstall Python, select this option.

b. If Python is installed correctly with tkinter, you might need to specify the full path to your Python installation when creating the virtual environment:
uv venv erag -p C:\path\to\your\python\python.exe
Replace C:\path\to\your\python\python.exe with the actual path to your Python executable.
General approach to resolving dependencies:
a. Activate your virtual environment:
.\erag\Scripts\activate
b. Try installing requirements one by one to identify problematic packages:
uv pip install package_name
c. If a specific package is causing issues, try installing it with pip instead of uv:
pip install package_name
d. Update pip and setuptools:
python -m pip install --upgrade pip setuptools
e. If issues persist, consider creating a new virtual environment without uv:
python -m venv erag_new
.\erag_new\Scripts\activate
pip install -r requirements.txt


Remember to run these commands in an elevated (administrator) command prompt if you encounter permission issues.
